repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: bash -c 'docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm tests'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
